### ISSUE TITLE
Patches to make histogrammar python 3 compatible

### ISSUE THREAD

**Issue by mbaak** [histogrammar/histogrammar-python#17]
Dear Jim,

I'm a senior data scientist in the big data & analytics team of KPMG The Netherlands
and found on your histogrammar package. We have the situation where we use 
multiple data tools for processing data (spark, pandas, root), and want to treat the filling
and plotting of histograms and consistently. So your packages would be perfect for us. 

(Incidentally I used to work in HEP like you, e.g. for cern as a fellow and staff for 7 years.)

So I tried histogrammer a bit and found that I needed several small patches for 
it to work properly (for us). These are:

1. Python 3 issues: 
- xrange -> range()
- has_key() -> in
- print -> print()
2. Fixed small bug in the at() function in sparselybin.py
3. Fixed a small bug in the TH2D constructor in plot/root.py, which needs explicit ints and floats. 
4. I added a few utility functions in plot/matplotlib.py in order to extract numpy 
type histograms (like you do for root as well). This is useful e.g. in case of rebinning 
or to calculate properties from the histograms directly (like percentiles).

I have attached a diff file wrt today's histogrammer-python master repo in git. 

The changes are straight-forward, but don't hesitate to let me know if you have any questions. 
We are considering to use histogrammer in our analysis code, so it would by great if you could merge this into the master branch.

Many thanks and best regards,
Max Baak

[histogrammer_python3_compatible.txt](https://github.com/histogrammar/histogrammar-python/files/855401/histogrammer_python3_compatible.txt)

**Comment by jpivarski** [comment]
I'm glad you're finding this useful, and thank you for your effort to make it Python-3 compatible.

However, I'm a little confused it that because Histogrammar should already be Python-3 compatible, and this is one of our continuous integration tests: https://travis-ci.org/histogrammar/histogrammar-python . We use expressions like `xrange` because histogrammar.util defines `if sys.version_info[0] > 2: xrange = range` (our mini version of "six"). We also had a campaign to ensure that `dict.keys()` and `dict.values()` are used as iterators, not lists.

Also, there shouldn't be _any_ print statements in the main repository. (Okay, I see a couple of valid cases in tests and debug functions: https://github.com/histogrammar/histogrammar-python/search?utf8=%E2%9C%93&q=print but they're all used with parentheses.)

But you found some bugs and I want to thank you for that. Apparently, our unit tests aren't stringent enough. Since you have a full diff, would it be possible to submit it as a pull request? (Fork, git-clone, apply the patch, and then pull-request.) If continuous integration accepts it, I'll pull it into our master and also merge it into our 1.x branch, which is the production-ready branch (what you get if you install from pip, for instance).

Cheers as a fellow ex-physicist! (That's how I consider myself as well.)

**Comment by jpivarski** [comment]
Oh, and if you have any examples you can share, I'm trying to encourage users to make them public Gists with the word "histogrammar" anywhere in the text. Then the "Search Gists" button in our documentation (http://histogrammar.org/docs/) should find them. It's low-key--- no need to explain context--- just a little extra help for a user who's searching for examples. Thanks!

**Comment by mbaak** [comment]
Hi Jim,

I just created a pull request. 

I found that the python 2-3 compatibility patches were not imported in the files 
in the directory histogrammar/plot, hence the conflicts that I ran into. 
I added the relevant import util line and now it works okay (included in the pull request.)

Besides ~3 small bug fixes, the other features I added are relatively small, meant to easily 
obtain numpy arrays for calculations, rebinning, or standalone plotting.

I’ll try to add a few plotting examples in the next few days.

Best, -Max

**Comment by jpivarski** [comment]
The pull request and continuous integration were successful, so now I'm additionally pulling the corrections into the 1.0.x branch. I'll release this as 1.0.7 once the next round of tests finish.

Thank you very much!

**Comment by mbaak** [comment]
Hi Jim,

While I'm at it, can I send a few more small but useful features?

Best, Max

Verstuurd vanaf mijn iPhone

**Comment by jpivarski** [comment]
Yes, please! I know that the bare specification of Histogrammar is a bit of a blank slate, but the embellishments should come from actual uses in data analysis, not speculations about what might be useful on my part.

Two requests, though: could you add them relative to the 1.0.x branch, which is right now synced with master, and describe them in the pull request text? I'll check the code differences as well, since these aren't simple bug fixes, but it would help for me to know what I'm looking for. Then I'll first merge your pull request into 1.0.x, then that into master, which is my usual order (I decided to make the master the "latest and greatest," so that 0.8.x, 1.0.x, and other branches tied to a version of the Histogrammar spec can continue to accrue bug fixes and features, even if there's a new spec.)

**Comment by mbaak** [comment]
Dear Jim,

I made a new pull request. I think that should be it from my side for now.
I will still send around a few plotting examples, but only later this week.

One more request. Could you perhaps release v1.0.7 for python 3.5 as well? 
I see that this is currently not tested, and likewise pip install doesn’t support it. 
Histogrammar works fine for me with python 3.5 though.
(We happen to use this in our group, so adding this would be much appreciated.)

Thanks and best regards,
-Max

**Comment by jpivarski** [comment]
I've released version 1.0.7 with your bug-fixes and new features. In this
release, I've also added Python 3.5 to the testing suite and eggs on PyPI.
All the documentation links should be up to date as well.

https://pypi.python.org/pypi/Histogrammar/1.0.7
https://github.com/histogrammar/histogrammar-python/releases/tag/1.0.7
http://histogrammar.org/python/1.0.7/
https://travis-ci.org/histogrammar/histogrammar-python/builds/213836278

Let me know if anything doesn't work.
Thanks!
-- Jim

**Comment by mbaak** [comment]
Dear Jim,

Many thanks for the speedy response!
I’ll let you know if something doesn’t work.

Best, -Max
