### ISSUE TITLE
NameError: name 'xrange' is not defined

### ISSUE THREAD

**Issue by debuggermalhotra** [histogrammar/histogrammar-python#28]
Hey everyone, I was going through the: 'Making plots with matplotlib' part of python docs and in the section: 'First Histogram' 
![screen shot 2017-05-02 at 3 36 19 am](https://cloud.githubusercontent.com/assets/13315992/25596773/99019a5c-2ee8-11e7-93f2-40e1fa05ed0b.png)

it throws an error:
![screen shot 2017-05-02 at 3 37 59 am](https://cloud.githubusercontent.com/assets/13315992/25596810/c61049b2-2ee8-11e7-88c6-65c75077d527.png)

I guess in data = [random.random() for i in xrange(2000)], data should be declared as: data = [random.random() for i in hg.xrange(2000)]

Plus after executing the ditto code from docs, the plot looks something likes this:

![screen shot 2017-05-02 at 3 40 42 am](https://cloud.githubusercontent.com/assets/13315992/25596880/24840b00-2ee9-11e7-8509-16865083de1b.png)
instead of:
![screen shot 2017-05-02 at 3 41 09 am](https://cloud.githubusercontent.com/assets/13315992/25596888/360bbb98-2ee9-11e7-8c9c-445faf8e41d4.png)

**Comment by jpivarski** [comment]
Is this reference to xrange in the tutorial code or in the Histogrammar code? Although we try to make Histogrammar Python 3 compliant, no such attempt was made for the documentation. There are probably also some `print` statements in there, too.

It would be hard to put the documentation into continuous integration to check for Python-2isms.

**Comment by jpivarski** [comment]
Oh, hi Chetan!

**Comment by debuggermalhotra** [comment]
Hello! 
Yeah, this is in reference to documentation code and the code was tested in IPython qtconsole with Python-3

**Comment by jpivarski** [comment]
You're free to edit the histogrammar-docs repository (on a separate branch with pull request, following standard practices), if you're interested. In fact, it would be a good exercise to check out and generate documentation with Jekyll because you'll probably be adding more at some point. But it's not a goal to support Python 3 in the documentation text, since the user can see that as they type it. Python 3 users shouldn't type "xrange."

I'm going to close this now, but you can open another one on histogrammar-docs, fix it, and then close it.
